# Generated by Django 4.0.4 on 2022-04-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_venue_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_name', models.CharField(max_length=255)),
                ('speaker_role', models.CharField(max_length=255)),
                ('speaker_topic', models.CharField(max_length=255)),
                ('speaker_email', models.EmailField(max_length=254, verbose_name='email address')),
                ('speaker_contact', models.IntegerField(default=1, verbose_name='phone number')),
            ],
        ),
    ]
